attack_real: True
real_label: 0
attack_fake: True
fake_label: 1

networks:
  - name: WANG_latent_r50
  - name: GRAG_latent_r50
  - name: CORV_latent_r50
  - name: CORV_latent_cn
  - name: OJHA_latent_clip
  - name: OJHA_latent_blip
  - name: GRAG_latent_clipe2e
  - name: CORV_latent_clipe2e

attacks:
  - name: UNI
    args:
      eps: 8
      max_iter_uni: 2
  - name: RFGSM
    args:
      max_iter: 10
      eps: 8
      alpha: 2
  - name: DIFGSM
    args:
      steps: 10
      eps: 8
      alpha: 2
  - name: pgdE
    args:
      eps: 8
      steps: 10